# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b472f0025358df5b78e835d27f29108cc9318bd821fd29cd0fc5b475b5db3631f0232c72cc11c2b6a644ddeea30941f0d83fa4a0d368e32bf4831753cf3a136

test:
  secret_key_base: e709c24d18a800b5f36ad8ec345bbe6971e3d232dc3ed7eb528f9fd2f9aee91d9c4184470b932ede3e51f00acc0d63044839cb6c2515f0c5df0b5ae8c6cf88c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
